### ISSUE TITLE
When viewing the next image in full screen state, the screen size is not correctly recognized

### ISSUE THREAD

**Issue by feilwt** [lambdan/imageviewer5#10]
I recently switched to an m1 macbook, xee can't view some pictures, I found imageviewer5 on Google, and imageviewer5 can open pictures very fast, this app can't zoom in and zoom out pictures, it seems When viewing the next picture in full screen, the screen size cannot be correctly recognized, and the size of the previous picture will be delayed.
(My English is not very good, I hope you can understand, thank you very much for making this app, I saw that the latest version was released last year, and I hope to keep updating. This is a good app)

**Comment by lambdan** [comment]
Sorry for the late reply. I've been busy and, well, frankly, Github didnt notify me and I don't check here often. Sorry about that.

I just uploaded 1.6.1, I hope it fixes it for you.

https://github.com/lambdan/imageviewer5/releases/tag/1.6.1

**Comment by feilwt** [comment]
Many Thanks, it's working fine! LOL
